package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuctionItem generated by hbm2java
 */
@Entity
@Table(name = "auction_item", catalog = "tam")
public class AuctionItem implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Auction auction;
	private String itemName;
	private double itemFare;
	private int itemCount;
	private double totalAmount;
	private String supliyerCompany;
	private String note;
	private String type;

	public AuctionItem() {
	}

	public AuctionItem(Auction auction, String itemName, double itemFare,
			int itemCount, double totalAmount, String supliyerCompany,
			String note, String type) {
		this.auction = auction;
		this.itemName = itemName;
		this.itemFare = itemFare;
		this.itemCount = itemCount;
		this.totalAmount = totalAmount;
		this.supliyerCompany = supliyerCompany;
		this.note = note;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "auction_id", nullable = false)
	public Auction getAuction() {
		return this.auction;
	}

	public void setAuction(Auction auction) {
		this.auction = auction;
	}

	@Column(name = "item_name", nullable = false, length = 45)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_fare", nullable = false, precision = 22, scale = 0)
	public double getItemFare() {
		return this.itemFare;
	}

	public void setItemFare(double itemFare) {
		this.itemFare = itemFare;
	}

	@Column(name = "�tem_count", nullable = false)
	public int getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(int itemCount) {
		this.itemCount = itemCount;
	}

	@Column(name = "total_amount", nullable = false, precision = 22, scale = 0)
	public double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "supliyer_company", nullable = false, length = 200)
	public String getSupliyerCompany() {
		return this.supliyerCompany;
	}

	public void setSupliyerCompany(String supliyerCompany) {
		this.supliyerCompany = supliyerCompany;
	}

	@Column(name = "note", nullable = false, length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
