package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "tam")
public class City implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String code;
	private Region region;
	private Country country;
	private String name;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);
	private Set<Port> ports = new HashSet<Port>(0);
	private Set<Museum> museums = new HashSet<Museum>(0);

	public City() {
	}

	public City(String code, Region region, Country country, String name) {
		this.code = code;
		this.region = region;
		this.country = country;
		this.name = name;
	}

	public City(String code, Region region, Country country, String name,
			Set<Hotel> hotels, Set<Port> ports, Set<Museum> museums) {
		this.code = code;
		this.region = region;
		this.country = country;
		this.name = name;
		this.hotels = hotels;
		this.ports = ports;
		this.museums = museums;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_code", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_code", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Port> getPorts() {
		return this.ports;
	}

	public void setPorts(Set<Port> ports) {
		this.ports = ports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Museum> getMuseums() {
		return this.museums;
	}

	public void setMuseums(Set<Museum> museums) {
		this.museums = museums;
	}

}
