package com.tam.model;
// default package
// Generated Mar 24, 2016 11:39:24 PM by Hibernate Tools 4.3.1.Final

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private String code;
	private String name;
	private String countryCode;
	private String regionCode;

	public City() {
	}

	public City(String code, String name, String countryCode, String regionCode) {
		this.code = code;
		this.name = name;
		this.countryCode = countryCode;
		this.regionCode = regionCode;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

}
