package com.tam.model;

// Generated Mar 29, 2015 10:00:22 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pax generated by hbm2java
 */
@Entity
@Table(name = "pax", catalog = "tam")
public class Pax implements java.io.Serializable {

	private Integer id;
	private ContactInfo contactInfo;
	private Pnr pnr;
	private String name;
	private String surname;
	private Date birthdate;
	private String passportNo;
	private Integer identificationNumber;
	private String company;
	private Date recordDate;
	private Set tickets = new HashSet(0);
	private Set tourPaxes = new HashSet(0);
	private Set hotelReservations = new HashSet(0);

	public Pax() {
	}

	public Pax(Pnr pnr, String name, String surname) {
		this.pnr = pnr;
		this.name = name;
		this.surname = surname;
	}

	public Pax(ContactInfo contactInfo, Pnr pnr, String name, String surname,
			Date birthdate, String passportNo, Integer identificationNumber,
			String company, Date recordDate, Set tickets, Set tourPaxes,
			Set hotelReservations) {
		this.contactInfo = contactInfo;
		this.pnr = pnr;
		this.name = name;
		this.surname = surname;
		this.birthdate = birthdate;
		this.passportNo = passportNo;
		this.identificationNumber = identificationNumber;
		this.company = company;
		this.recordDate = recordDate;
		this.tickets = tickets;
		this.tourPaxes = tourPaxes;
		this.hotelReservations = hotelReservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_info_id")
	public ContactInfo getContactInfo() {
		return this.contactInfo;
	}

	public void setContactInfo(ContactInfo contactInfo) {
		this.contactInfo = contactInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pnr_id", nullable = false)
	public Pnr getPnr() {
		return this.pnr;
	}

	public void setPnr(Pnr pnr) {
		this.pnr = pnr;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 45)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "passport_no", length = 45)
	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	@Column(name = "identification_number")
	public Integer getIdentificationNumber() {
		return this.identificationNumber;
	}

	public void setIdentificationNumber(Integer identificationNumber) {
		this.identificationNumber = identificationNumber;
	}

	@Column(name = "company", length = 45)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_date", length = 19)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pax")
	public Set getTickets() {
		return this.tickets;
	}

	public void setTickets(Set tickets) {
		this.tickets = tickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pax")
	public Set getTourPaxes() {
		return this.tourPaxes;
	}

	public void setTourPaxes(Set tourPaxes) {
		this.tourPaxes = tourPaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pax")
	public Set getHotelReservations() {
		return this.hotelReservations;
	}

	public void setHotelReservations(Set hotelReservations) {
		this.hotelReservations = hotelReservations;
	}

}
