package com.tam.model;

// Generated Mar 29, 2015 10:00:22 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name = "payment_type", catalog = "tam")
public class PaymentType implements java.io.Serializable {

	private String code;
	private String explanation;
	private Set tickets = new HashSet(0);

	public PaymentType() {
	}

	public PaymentType(String code) {
		this.code = code;
	}

	public PaymentType(String code, String explanation, Set tickets) {
		this.code = code;
		this.explanation = explanation;
		this.tickets = tickets;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "explanation", length = 200)
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentType")
	public Set getTickets() {
		return this.tickets;
	}

	public void setTickets(Set tickets) {
		this.tickets = tickets;
	}

}
