package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Process generated by hbm2java
 */
@Entity
@Table(name = "process", catalog = "tam")
public class Process implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String code;
	private String explanation;
	private Set<Role> roles = new HashSet<Role>(0);

	public Process() {
	}

	public Process(String code) {
		this.code = code;
	}

	public Process(String code, String explanation, Set<Role> roles) {
		this.code = code;
		this.explanation = explanation;
		this.roles = roles;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "explanation", length = 100)
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_process", catalog = "tam", joinColumns = { @JoinColumn(name = "process_code", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_code", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
