package com.tam.model;
// Generated Oct 26, 2016 12:52:47 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "tam")
public class Region implements java.io.Serializable {

	private int id;
	private Country country;
	private String regionName;
	private Set<City> cities = new HashSet<City>(0);

	public Region() {
	}

	public Region(int id, Country country, String regionName) {
		this.id = id;
		this.country = country;
		this.regionName = regionName;
	}

	public Region(int id, Country country, String regionName, Set<City> cities) {
		this.id = id;
		this.country = country;
		this.regionName = regionName;
		this.cities = cities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_code", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "region_name", nullable = false, length = 45)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
