package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restorant generated by hbm2java
 */
@Entity
@Table(name = "restorant", catalog = "tam")
public class Restorant implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String name;
	private String adsress;
	private String phone;
	private String email;
	private Set<TourRestorant> tourRestorants = new HashSet<TourRestorant>(0);

	public Restorant() {
	}

	public Restorant(String name) {
		this.name = name;
	}

	public Restorant(String name, String adsress, String phone, String email,
			Set<TourRestorant> tourRestorants) {
		this.name = name;
		this.adsress = adsress;
		this.phone = phone;
		this.email = email;
		this.tourRestorants = tourRestorants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "adsress", length = 200)
	public String getAdsress() {
		return this.adsress;
	}

	public void setAdsress(String adsress) {
		this.adsress = adsress;
	}

	@Column(name = "phone", length = 18)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restorant")
	public Set<TourRestorant> getTourRestorants() {
		return this.tourRestorants;
	}

	public void setTourRestorants(Set<TourRestorant> tourRestorants) {
		this.tourRestorants = tourRestorants;
	}

}
