package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TourPax generated by hbm2java
 */
@Entity
@Table(name = "tour_pax", catalog = "tam")
public class TourPax implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private TourPaxId id;
	private Pax pax;
	private User user;
	private Tour tour;

	public TourPax() {
	}

	public TourPax(TourPaxId id, Pax pax, User user, Tour tour) {
		this.id = id;
		this.pax = pax;
		this.user = user;
		this.tour = tour;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tourId", column = @Column(name = "tour_id", nullable = false)),
			@AttributeOverride(name = "paxId", column = @Column(name = "pax_id", nullable = false)) })
	public TourPaxId getId() {
		return this.id;
	}

	public void setId(TourPaxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pax_id", nullable = false, insertable = false, updatable = false)
	public Pax getPax() {
		return this.pax;
	}

	public void setPax(Pax pax) {
		this.pax = pax;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tour_id", nullable = false, insertable = false, updatable = false)
	public Tour getTour() {
		return this.tour;
	}

	public void setTour(Tour tour) {
		this.tour = tour;
	}

}
