package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TourPaxId generated by hbm2java
 */
@Embeddable
public class TourPaxId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int tourId;
	private int paxId;

	public TourPaxId() {
	}

	public TourPaxId(int tourId, int paxId) {
		this.tourId = tourId;
		this.paxId = paxId;
	}

	@Column(name = "tour_id", nullable = false)
	public int getTourId() {
		return this.tourId;
	}

	public void setTourId(int tourId) {
		this.tourId = tourId;
	}

	@Column(name = "pax_id", nullable = false)
	public int getPaxId() {
		return this.paxId;
	}

	public void setPaxId(int paxId) {
		this.paxId = paxId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TourPaxId))
			return false;
		TourPaxId castOther = (TourPaxId) other;

		return (this.getTourId() == castOther.getTourId())
				&& (this.getPaxId() == castOther.getPaxId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTourId();
		result = 37 * result + this.getPaxId();
		return result;
	}

}
