package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuctionPayment generated by hbm2java
 */
@Entity
@Table(name = "auction_payment", catalog = "tam")
public class AuctionPayment implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Auction auction;
	private String name;
	private Double amount;
	private String currency;
	private String note;
	private String type;
	private Date opsDate;

	public AuctionPayment() {
	}

	public AuctionPayment(Date opsDate) {
		this.opsDate = opsDate;
	}

	public AuctionPayment(Auction auction, String name, Double amount,
			String currency, String note, String type, Date opsDate) {
		this.auction = auction;
		this.name = name;
		this.amount = amount;
		this.currency = currency;
		this.note = note;
		this.type = type;
		this.opsDate = opsDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "auction_id")
	public Auction getAuction() {
		return this.auction;
	}

	public void setAuction(Auction auction) {
		this.auction = auction;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "currency", length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "type", length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ops_date", nullable = false, length = 19)
	public Date getOpsDate() {
		return this.opsDate;
	}

	public void setOpsDate(Date opsDate) {
		this.opsDate = opsDate;
	}

}
