package com.tam.model;

// Generated Mar 29, 2015 10:00:22 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auction generated by hbm2java
 */
@Entity
@Table(name = "auction", catalog = "tam")
public class Auction implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String auctionName;
	private String registryNo;
	private String coordinatorName;
	private String coordinatorSurname;
	private String orginizationName;
	private Date auctionDate;
	private Date contractDate;
	private Date kickOffDate;
	private Date dueDate;
	private Double estimatedCost;
	private Double contractAmount;
	private Double estimatedProfit;
	private Set<AuctionPayment> auctionPayments = new HashSet<AuctionPayment>(0);
	private Set<AuctionItem> auctionItems = new HashSet<AuctionItem>(0);

	public Auction() {
	}

	public Auction(String auctionName, String registryNo,
			String coordinatorName, String coordinatorSurname,
			String orginizationName, Date auctionDate, Date contractDate,
			Date kickOffDate, Date dueDate, Double estimatedCost,
			Double contractAmount, Double estimatedProfit, Set<AuctionPayment> auctionPayments,
			Set<AuctionItem> auctionItems) {
		
		this.auctionName = auctionName;
		this.registryNo = registryNo;
		this.coordinatorName = coordinatorName;
		this.coordinatorSurname = coordinatorSurname;
		this.orginizationName = orginizationName;
		this.auctionDate = auctionDate;
		this.contractDate = contractDate;
		this.kickOffDate = kickOffDate;
		this.dueDate = dueDate;
		this.estimatedCost = estimatedCost;
		this.contractAmount = contractAmount;
		this.estimatedProfit = estimatedProfit;
		this.auctionPayments = auctionPayments;
		this.auctionItems = auctionItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "auction_name", length = 45)
	public String getAuctionName() {
		return this.auctionName;
	}

	public void setAuctionName(String auctionName) {
		this.auctionName = auctionName;
	}

	@Column(name = "registry_no", length = 20)
	public String getRegistryNo() {
		return this.registryNo;
	}

	public void setRegistryNo(String registryNo) {
		this.registryNo = registryNo;
	}

	@Column(name = "coordinator_name", length = 45)
	public String getCoordinatorName() {
		return this.coordinatorName;
	}

	public void setCoordinatorName(String coordinatorName) {
		this.coordinatorName = coordinatorName;
	}

	@Column(name = "coordinator_surname", length = 45)
	public String getCoordinatorSurname() {
		return this.coordinatorSurname;
	}

	public void setCoordinatorSurname(String coordinatorSurname) {
		this.coordinatorSurname = coordinatorSurname;
	}

	@Column(name = "orginization_name", length = 45)
	public String getOrginizationName() {
		return this.orginizationName;
	}

	public void setOrginizationName(String orginizationName) {
		this.orginizationName = orginizationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "auction_date", length = 19)
	public Date getAuctionDate() {
		return this.auctionDate;
	}

	public void setAuctionDate(Date auctionDate) {
		this.auctionDate = auctionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contract_date", length = 19)
	public Date getContractDate() {
		return this.contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "kick_off_date", length = 19)
	public Date getKickOffDate() {
		return this.kickOffDate;
	}

	public void setKickOffDate(Date kickOffDate) {
		this.kickOffDate = kickOffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_date", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "estimated_cost", precision = 22, scale = 0)
	public Double getEstimatedCost() {
		return this.estimatedCost;
	}

	public void setEstimatedCost(Double estimatedCost) {
		this.estimatedCost = estimatedCost;
	}

	@Column(name = "contract_amount", precision = 22, scale = 0)
	public Double getContractAmount() {
		return this.contractAmount;
	}

	public void setContractAmount(Double contractAmount) {
		this.contractAmount = contractAmount;
	}

	@Column(name = "estimated_profit", precision = 22, scale = 0)
	public Double getEstimatedProfit() {
		return this.estimatedProfit;
	}

	public void setEstimatedProfit(Double estimatedProfit) {
		this.estimatedProfit = estimatedProfit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auction")
	public Set<AuctionPayment> getAuctionPayments() {
		return this.auctionPayments;
	}

	public void setAuctionPayments(Set<AuctionPayment> auctionPayments) {
		this.auctionPayments = auctionPayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auction")
	public Set<AuctionItem> getAuctionItems() {
		return this.auctionItems;
	}

	public void setAuctionItems(Set<AuctionItem> auctionItems) {
		this.auctionItems = auctionItems;
	}

}
