package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", catalog = "tam")
public class Coupon implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Segment segment;
	private Ticket ticket;
	private int cpnNo;
	private String cpnStatus;
	private Date recordDate;

	public Coupon() {
	}

	public Coupon(Segment segment, Ticket ticket, int cpnNo, String cpnStatus) {
		this.segment = segment;
		this.ticket = ticket;
		this.cpnNo = cpnNo;
		this.cpnStatus = cpnStatus;
	}

	public Coupon(Segment segment, Ticket ticket, int cpnNo, String cpnStatus,
			Date recordDate) {
		this.segment = segment;
		this.ticket = ticket;
		this.cpnNo = cpnNo;
		this.cpnStatus = cpnStatus;
		this.recordDate = recordDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "segment_id", nullable = true)
	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tkt_id", nullable = true)
	public Ticket getTicket() {
		return this.ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}

	@Column(name = "cpn_no", nullable = true)
	public int getCpnNo() {
		return this.cpnNo;
	}

	public void setCpnNo(int cpnNo) {
		this.cpnNo = cpnNo;
	}

	@Column(name = "cpn_status", nullable = true, length = 1)
	public String getCpnStatus() {
		return this.cpnStatus;
	}

	public void setCpnStatus(String cpnStatus) {
		this.cpnStatus = cpnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_date", length = 19)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

}
