package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", catalog = "tam")
public class Hotel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private City city;
	private String name;
	private String address;
	private String email;
	private String phone;
	private Set<HotelFare> hotelFares = new HashSet<HotelFare>(0);
	private Set<HotelReservation> hotelReservations = new HashSet<HotelReservation>(0);
	private Set<Tour> tours = new HashSet<Tour>(0);

	public Hotel() {
	}

	public Hotel(City city, String name, String address) {
		this.city = city;
		this.name = name;
		this.address = address;
	}

	public Hotel(City city, String name, String address, String email,
			String phone, Set<HotelFare> hotelFares, Set<HotelReservation> hotelReservations, Set<Tour> tours) {
		this.city = city;
		this.name = name;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.hotelFares = hotelFares;
		this.hotelReservations = hotelReservations;
		this.tours = tours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_code", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 18)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<HotelFare> getHotelFares() {
		return this.hotelFares;
	}

	public void setHotelFares(Set<HotelFare> hotelFares) {
		this.hotelFares = hotelFares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<HotelReservation> getHotelReservations() {
		return this.hotelReservations;
	}

	public void setHotelReservations(Set<HotelReservation> hotelReservations) {
		this.hotelReservations = hotelReservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Tour> getTours() {
		return this.tours;
	}

	public void setTours(Set<Tour> tours) {
		this.tours = tours;
	}

}
