package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HotelReservation generated by hbm2java
 */
@Entity
@Table(name = "hotel_reservation", catalog = "tam")
public class HotelReservation implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Pnr pnr;
	private Hotel hotel;
	private Pax pax;
	private Date dateFrom;
	private Date dateUntil;
	private int roomCount;

	public HotelReservation() {
	}

	public HotelReservation(Pnr pnr, Hotel hotel, Pax pax, Date dateFrom,
			Date dateUntil, int roomCount) {
		this.pnr = pnr;
		this.hotel = hotel;
		this.pax = pax;
		this.dateFrom = dateFrom;
		this.dateUntil = dateUntil;
		this.roomCount = roomCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pnr_id", nullable = false)
	public Pnr getPnr() {
		return this.pnr;
	}

	public void setPnr(Pnr pnr) {
		this.pnr = pnr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "traveler_id", nullable = false)
	public Pax getPax() {
		return this.pax;
	}

	public void setPax(Pax pax) {
		this.pax = pax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", nullable = false, length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_until", nullable = false, length = 10)
	public Date getDateUntil() {
		return this.dateUntil;
	}

	public void setDateUntil(Date dateUntil) {
		this.dateUntil = dateUntil;
	}

	@Column(name = "room_count", nullable = false)
	public int getRoomCount() {
		return this.roomCount;
	}

	public void setRoomCount(int roomCount) {
		this.roomCount = roomCount;
	}

}
