package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HotelFare generated by hbm2java
 */
@Entity
@Table(name = "hotel_fare", catalog = "tam")
public class HotelFare implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Hotel hotel;
	private String roomTypeCode;
	private double buyingFare;
	private double sellingFare;
	private double gateFare;

	public HotelFare() {
	}

	public HotelFare(Hotel hotel, String roomTypeCode, double buyingFare,
			double sellingFare, double gateFare) {
		this.hotel = hotel;
		this.roomTypeCode = roomTypeCode;
		this.buyingFare = buyingFare;
		this.sellingFare = sellingFare;
		this.gateFare = gateFare;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "room_type_code", nullable = false, length = 20)
	public String getRoomTypeCode() {
		return this.roomTypeCode;
	}

	public void setRoomTypeCode(String roomTypeCode) {
		this.roomTypeCode = roomTypeCode;
	}

	@Column(name = "buying_fare", nullable = false, precision = 22, scale = 0)
	public double getBuyingFare() {
		return this.buyingFare;
	}

	public void setBuyingFare(double buyingFare) {
		this.buyingFare = buyingFare;
	}

	@Column(name = "selling_fare", nullable = false, precision = 22, scale = 0)
	public double getSellingFare() {
		return this.sellingFare;
	}

	public void setSellingFare(double sellingFare) {
		this.sellingFare = sellingFare;
	}

	@Column(name = "gate_fare", nullable = false, precision = 22, scale = 0)
	public double getGateFare() {
		return this.gateFare;
	}

	public void setGateFare(double gateFare) {
		this.gateFare = gateFare;
	}

}
