package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pnr generated by hbm2java
 */
@Entity
@Table(name = "pnr", catalog = "tam")
public class Pnr implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private User user;
	private String pnrNo;
	private Date optionDate;
	private String status;
	private String type;
	private String cancelReason;
	private String note;
	private Date recordDate;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);
	private Set<HotelReservation> hotelReservations = new HashSet<HotelReservation>(0);
	private Set<Pax> paxes = new HashSet<Pax>(0);

	public Pnr() {
	}

	public Pnr(User user, String pnrNo, String status, Date recordDate) {
		this.user = user;
		this.pnrNo = pnrNo;
		this.status = status;
		this.recordDate = recordDate;
	}

	public Pnr(User user, String pnrNo, Date optionDate, String status,
			String type, String cancelReason, String note, Date recordDate,
			Set<Ticket> tickets, Set<HotelReservation> hotelReservations, Set<Pax> paxes) {
		this.user = user;
		this.pnrNo = pnrNo;
		this.optionDate = optionDate;
		this.status = status;
		this.type = type;
		this.cancelReason = cancelReason;
		this.note = note;
		this.recordDate = recordDate;
		this.tickets = tickets;
		this.hotelReservations = hotelReservations;
		this.paxes = paxes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "pnr_no", nullable = false, length = 6)
	public String getPnrNo() {
		return this.pnrNo;
	}

	public void setPnrNo(String pnrNo) {
		this.pnrNo = pnrNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "option_date", length = 19)
	public Date getOptionDate() {
		return this.optionDate;
	}

	public void setOptionDate(Date optionDate) {
		this.optionDate = optionDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "type", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "cancel_reason", length = 200)
	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_date", nullable = false, length = 19)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnr")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnr")
	public Set<HotelReservation> getHotelReservations() {
		return this.hotelReservations;
	}

	public void setHotelReservations(Set<HotelReservation> hotelReservations) {
		this.hotelReservations = hotelReservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pnr")
	public Set<Pax> getPaxes() {
		return this.paxes;
	}

	public void setPaxes(Set<Pax> paxes) {
		this.paxes = paxes;
	}

}
