package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;


/**
 * Role generated by hbm2java
 */
@SuppressWarnings("unused")
@Entity
@Table(name = "role", catalog = "tam")
//@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, region="reference")
public class Role implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String code;
	private String explanation;
	private Set<User> users = new HashSet<User>(0);
	private Set<Process> processes = new HashSet<Process>(0);

	public Role() {
	}

	public Role(String code) {
		this.code = code;
	}

	public Role(String code, String explanation, Set<User> users, Set<Process> processes) {
		this.code = code;
		this.explanation = explanation;
		this.users = users;
		this.processes = processes;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "explanation", length = 100)
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", catalog = "tam",
				joinColumns = { @JoinColumn(name = "role_code", nullable = false, updatable = false) },
				inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_process", catalog = "tam", joinColumns = { @JoinColumn(name = "role_code", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "process_code", nullable = false, updatable = false) })
	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

}
