package com.tam.model;

import static javax.persistence.GenerationType.IDENTITY;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "tam")
public class Ticket implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	
	private String tktNo;
	private User user;
	private PaymentType paymentType;
	private Pnr pnr;
	private Pax pax;
	private String status;
	private Date dos;
	private Date dor;
	private double buyingAmount;
	private String buyingCurrency;
	private double sellingAmount;
	private String sellingCurrency;
	private Set<Coupon> coupons = new HashSet<Coupon>(0);

	public Ticket() {
	}

	public Ticket(String tktNo, User user, PaymentType paymentType, Pax pax,
			String status, Date dos, double buyingAmount,
			String buyingCurrency, double sellingAmount, String sellingCurrency) {
		this.tktNo = tktNo;
		this.user = user;
		this.paymentType = paymentType;
		this.pax = pax;
		this.status = status;
		this.dos = dos;
		this.buyingAmount = buyingAmount;
		this.buyingCurrency = buyingCurrency;
		this.sellingAmount = sellingAmount;
		this.sellingCurrency = sellingCurrency;
	}

	public Ticket(String tktNo, User user, PaymentType paymentType, Pnr pnr,
			Pax pax, String status, Date dos, Date dor, double buyingAmount,
			String buyingCurrency, double sellingAmount,
			String sellingCurrency, Set<Coupon> coupons) {
		this.tktNo = tktNo;
		this.user = user;
		this.paymentType = paymentType;
		this.pnr = pnr;
		this.pax = pax;
		this.status = status;
		this.dos = dos;
		this.dor = dor;
		this.buyingAmount = buyingAmount;
		this.buyingCurrency = buyingCurrency;
		this.sellingAmount = sellingAmount;
		this.sellingCurrency = sellingCurrency;
		this.coupons = coupons;
	}
	
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = true)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "tkt_no", unique = true, nullable = true, length = 13)
	public String getTktNo() {
		return this.tktNo;
	}

	public void setTktNo(String tktNo) {
		this.tktNo = tktNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = true)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_type_code", nullable = true)
	public PaymentType getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pnr_id")
	public Pnr getPnr() {
		return this.pnr;
	}

	public void setPnr(Pnr pnr) {
		this.pnr = pnr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "traveler_id", nullable = true)
	public Pax getPax() {
		return this.pax;
	}

	public void setPax(Pax pax) {
		this.pax = pax;
	}

	@Column(name = "status", nullable = true, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "dos", nullable = true, length = 19)
	public Date getDos() {
		return this.dos;
	}

	public void setDos(Date dos) {
		this.dos = dos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dor", length = 19)
	public Date getDor() {
		return this.dor;
	}

	public void setDor(Date dor) {
		this.dor = dor;
	}

	@Column(name = "buying_amount", nullable = true, precision = 22, scale = 0)
	public double getBuyingAmount() {
		return this.buyingAmount;
	}

	public void setBuyingAmount(double buyingAmount) {
		this.buyingAmount = buyingAmount;
	}

	@Column(name = "buying_currency", nullable = true, length = 3)
	public String getBuyingCurrency() {
		return this.buyingCurrency;
	}

	public void setBuyingCurrency(String buyingCurrency) {
		this.buyingCurrency = buyingCurrency;
	}

	@Column(name = "selling_amount", nullable = true, precision = 22, scale = 0)
	public double getSellingAmount() {
		return this.sellingAmount;
	}

	public void setSellingAmount(double sellingAmount) {
		this.sellingAmount = sellingAmount;
	}

	@Column(name = "selling_currency", nullable = true, length = 3)
	public String getSellingCurrency() {
		return this.sellingCurrency;
	}

	public void setSellingCurrency(String sellingCurrency) {
		this.sellingCurrency = sellingCurrency;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	public Set<Coupon> getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set<Coupon> coupons) {
		this.coupons = coupons;
	}

}
