package com.tam.model;

// Generated Mar 29, 2015 10:00:22 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "tam")
public class User implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	
	private Integer id;
	private String userName;
	private String userPassword;
	private String fullName;
	private String disable;
	private Date recordDate;
	private Set<Role> userRoles = new HashSet<Role>(0);
	private Set<TourPax> tourPaxes = new HashSet<TourPax>(0);
	private Set<Pnr> pnrs = new HashSet<Pnr>(0);
	private Set<Tour> tours = new HashSet<Tour>(0);
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public User() {
	}

	public User(String userName, String userPassword, String fullName,
			String disable, Date recordDate) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.fullName = fullName;
		this.disable = disable;
		this.recordDate = recordDate;
	}

	public User(String userName, String userPassword, String fullName,
			String disable, Date recordDate, Set<Role> userRoles, Set<TourPax> tourPaxes,
			Set<Pnr> pnrs, Set<Tour> tours, Set<Ticket> tickets) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.fullName = fullName;
		this.disable = disable;
		this.recordDate = recordDate;
		this.userRoles = userRoles;
		this.tourPaxes = tourPaxes;
		this.pnrs = pnrs;
		this.tours = tours;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_password", nullable = false, length = 45)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "full_name", nullable = false, length = 45)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "disable", nullable = false, length = 1)
	public String getDisable() {
		return this.disable;
	}

	public void setDisable(String disable) {
		this.disable = disable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_date", nullable = false, length = 19)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name="user_role",
            joinColumns={@JoinColumn(name="user_id")}, 
            inverseJoinColumns={@JoinColumn(name="role_code")})
	public Set<Role> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<Role> userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<TourPax> getTourPaxes() {
		return this.tourPaxes;
	}

	public void setTourPaxes(Set<TourPax> tourPaxes) {
		this.tourPaxes = tourPaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Pnr> getPnrs() {
		return this.pnrs;
	}

	public void setPnrs(Set<Pnr> pnrs) {
		this.pnrs = pnrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Tour> getTours() {
		return this.tours;
	}

	public void setTours(Set<Tour> tours) {
		this.tours = tours;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
